### PR TITLE
[WIP] Add key-findings page for final report

### PR DESCRIPTION
**Pull request by tekd**
I started the key-findings page for the final report and I have a few questions. I am using the _case-studies as a template and just pasting all of the html content that @claudioccm provided. I used 'set case' to point to an arbitrary case so any references to them won't break but this will be deleted.
#### Header info

The following information is usually contained in the header but the final report doesn't include it:
- Impact Type
- Sector
- Location
- Read Time
- Full Read Time

Can we confirm we don't want this info?
#### Colors

Colors are determined by impact type in the template--which one should I use?
#### Style
- Since we're going to use a vertical scroll spy, do we still want the sections to be 'expandable' or do we want all of the content to be present on the page? FYI right now everything is expandable, which for some reason hid everything but the header.

### CODE REVIEW

**Comment by ghost** [comment]
as far as i understand, you can & should remove `set case` for the final report / findings template safely. you might have to update the template, but this is how it should be if we aren't pulling any data. unless there is some other problem with this you are looking at that i am not thinking of, in which case, just let me know about it.

i can confirm we don't need
*Impact Type
*Sector
*Location
@chrswng or batu could confirm whether we want read time information on the final report. i think it makes sense even if we don't display.  one thing we actually need to do is to create something to calculate this read time based on the actual word count instead of the arbitrary value we put in there. lowest tech option would be to manually calculate it and update the yaml, better solution might be a JS or static workflow based word counting script, if we have time to do this.

colors, talk to @claudioccm 

for scrollspy, even though it seems kind of redundant, i think we should still keep in the partially collapsed sections, because this is supposed to facilitate a 'quick read'. if you can come up with a smarter solution that still keeps the ux of 'quick read' available and makes a little more sense with scrollspy, throw it up

**Comment by chrswng** [comment]
agree with mark on keeping expand/collapse per section even with scroll spy

**Comment by chrswng** [comment]
i guess I'd keep in read time if for no other reason than consistency with the other case studies. Anyone got time to read it and report back how long it took? :)

**Comment by ghost** [comment]
well in theory we can and might want to calculate an average read time based on the word count, since everyone's actual read time will be different. there are tons of low tech tools / online calculator things to do this pretty easily

**Comment by tekd** [comment]
Ok, I'll move forward with expandable and scroll spy. 

We will also need a banner image.

**Comment by chrswng** [comment]
I think probably use the banner image from homepage for this? That kinda makes sense to me and brings everything back sort of full circle. I'll ask stefaan for sure though.

**Comment by ghost** [comment]
jw, is there an 'alt' image from the stock site that is like a similar shot or another shot of the same scene at a different time / angle sort of thing?

if so i feel like that would be really polished

**Comment by tekd** [comment]
Hello! I have added the following to the key resources page. There are a number of styling issues for the html and css that I am working on and I need to refactor the JS, but here is where everything is at.

### Responsive issues
- Where should the scrollspy menu go for mobile devices? Hide it for now and then turn it into a dropdown  if there is time?
- The page is separated into two cols within a row, `medium-3 columns e-scrollspy` and `large-8 columns end long-reading`. I am adding an offset to the `.long-readings` column when the sticky nav kicks in but then it is no longer responsive.

### Sticky Nav
- When you scroll past the header, a sticky nav fixes itself to the top of the viewable section. The transition is a little awkward and I am working on it.
- It's currently moving past the footer when you scroll all the way down.

### Scroll Spy
-  Needs refactoring
- My scroll bindings are off, i.e. it will highlight a section before it gets to the top of the page, and I am working on that.

### Content Issues
- The mockup from @claudioccm has "Key Remaining Questions" as a scroll menu item but the html markup doesn't have that content in a separate section. Add as new section?
- The special thanks footnote in the header is usually an \* but here it starts as 1. Leave as is?
- Footnote 6 in this section refers to a footnote in Appendix I. Appendices have their own set of footnotes starting from 1.
- Section "V. What Are the Challenges to Open Data Making an Impact?" is missing a graphic: "Box: Supply Vs. Demand Trajectories (Graphics TBD)". There are also 3 textboxes--I wanted to confirm that I would style these.

**Pull request merged**
